### ISSUE TITLE
The default version of Ansible in Ubuntu 14.04 does not work well with Docker

### ISSUE THREAD

**Issue by tzok** [indigo-dc/os-sshd#6]
In the 1.5.4 version of Ansible, which is a default one in Ubuntu 14.04, there was a bug which prevents from running a playbook on a localhost if the inventory is untouched. Such situation is true for Docker images, so effectively this version of Ansible disallows to have Ansible role and just apply a playbook in Docker. This concerns e.g. INDIGO Docker Kepler

When you install the latest Ansible from PPA, the problem is gone. Can you add this to the image?

**Comment by gmolto** [comment]
The INDIGO-DataCloud's Docker Image for Ubuntu 14.04 already has installed Ansible version 2.1.0.0 from the INDIGO-DataCloud's package repositories:

docker run --rm -ti indigodatacloud/ubuntu-sshd:14.04 bash
root@e68d00fdea09:/# ansible --version
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

Best regards.

**Comment by tzok** [comment]
Right, I was using an old image from my local disk:

```
$ docker run --rm -ti indigodatacloud/ubuntu-sshd:14.04 bash
root@2b45785c52c7:/# ansible --version
ansible 1.5.4
```

After `docker pull` I get correct result:

```
$ docker run --rm -ti indigodatacloud/ubuntu-sshd:14.04 bash
root@1f0f6b945892:/# ansible --version
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

Thanks for quick clarification!
